name: RemoveChest
main: net.erbros.RemoveChest.RemoveChest
version: 0.1.1
author: Erbros
website: www.erbros.net
commands:
  removechest:
    description: Remove a chest, furnace or dispenser.
    usage: /<command>
    aliases: []
permissions:
  removechest.remove:
    description: Lets the user reload the configuration.
    default: op
